### ISSUE TITLE
Couldn't reach the host!

### ISSUE THREAD

**Issue by Emdad05** [h33tlit/Jbin-website-secret-scraper#2]
![Screenshot_2023-04-08-07-29-15-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/99329205/230698353-191b081b-e12b-4ae7-aed8-e774ee8eedae.jpg)
I am getting this err

**Comment by h33tlit** [comment]
Hi Can you give me the debug error message?

**Comment by h33tlit** [comment]
It seems like you put wrong format for the domain, Can you please check and resubmit the issue?
